# Generated by Django 5.1.3 on 2024-12-27 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('shipping', models.IntegerField(default=0)),
                ('grandtotal', models.IntegerField(default=0)),
                ('customname', models.CharField(default='', max_length=50)),
                ('customphone', models.CharField(default='', max_length=50)),
                ('customaddress', models.CharField(default='', max_length=100)),
                ('customemail', models.EmailField(default='', max_length=254)),
                ('paytype', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(blank=True, default='', max_length=100)),
                ('pimage', models.CharField(blank=True, default='', max_length=200)),
                ('pprice', models.IntegerField(default=0)),
                ('member_price', models.IntegerField(default=0)),
                ('pdescription', models.TextField(blank=True, default='')),
                ('hot', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(blank=True, default='', max_length=100)),
                ('pimage', models.CharField(blank=True, default='', max_length=200)),
                ('unitprice', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('dorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ordermodel')),
            ],
        ),
    ]
